# Generated by Django 5.0.3 on 2024-03-05 11:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk_id', models.IntegerField()),
                ('stk_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_ID', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_pwd', models.CharField(max_length=500)),
                ('user_email', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_till_date', models.IntegerField()),
                ('date_of_pricing', models.DateTimeField(default=0)),
                ('stk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_priceable', to='core.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Positiontable',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('psn_qty', models.IntegerField()),
                ('last_price', models.IntegerField()),
                ('weighed_price', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_postable', to=settings.AUTH_USER_MODEL)),
                ('stk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_postable', to='core.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Pnltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnl', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pnl', to=settings.AUTH_USER_MODEL)),
                ('stk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_pnl', to='core.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Transactiontable',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('txn_qty', models.IntegerField()),
                ('txn_price', models.IntegerField()),
                ('market_value', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('stk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transtable', to='core.stocks')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transtable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
